### ISSUE TITLE
Duplicated 'note' column in table 'transact'

### ISSUE THREAD

**Issue by kirillsulim** [alttch/finac#2]
I'm trying to write simple telegram bot for accounting. However when I try to init sqlite database with `finac.init("accountant.db")` I get `sqlalchemy.exc.DuplicateColumnError: A column with name 'note' is already present in table 'transact'.`

Full stacktrace:
```
Traceback (most recent call last):
  File "/home/su0/git/kirillsulim/accountant-tg-bot/src/accountant.py", line 28, in <module>
    a = Accountant(Logger("bla"))
  File "/home/su0/git/kirillsulim/accountant-tg-bot/src/accountant.py", line 24, in __init__
    finac.init(str(self.DB_PATH))
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/finac/core.py", line 618, in init
    init_db(_db.engine)
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/finac/db_set.py", line 64, in init_db
    transact = Table('transact',
  File "<string>", line 2, in __new__
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/util/deprecations.py", line 283, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 435, in __new__
    return cls._new(*args, **kw)
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 489, in _new
    with util.safe_reraise():
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 485, in _new
    table.__init__(name, metadata, *args, _no_init=False, **kw)
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 877, in __init__
    self._init_items(
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 230, in _init_items
    spwd(self, **kw)
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1328, in _set_parent_with_dispatch
    self._set_parent(parent, **kw)
  File "/home/su0/git/kirillsulim/accountant-tg-bot/.venv/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 2341, in _set_parent
    raise exc.DuplicateColumnError(
sqlalchemy.exc.DuplicateColumnError: A column with name 'note' is already present in table 'transact'.
```

Possible source of issue is double definition of column note https://github.com/alttch/finac/blob/956dd3bda113cb65d57d6ffa5568440a87656177/finac/db_set.py#L75 

However this double definition exists for a long time so I am not sure about that.

**Comment by PiotrCzapla** [comment]
my guess is that he is not using the library to create new tables, or the issue  is ignored by some  sqls. Either way after fixing it does not work with recent sqlalchemy too. It looks like the project is not maintained anymore.

**Comment by divi255** [comment]
good day,

yep the public module hasn't been updated for long. going to fix it today or tomorrow and make compatible with the new alchemy
